client/urls.py
from django.urls import path

from . import views
from .apps import ClientConfig
from .services import start_scheduler
from .views import HomeView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingListView, \
    MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, MessageListView, MessageCreateView, \
    MessageUpdateView, MessageDetailView, MessageDeleteView, LogListView

app_name = ClientConfig.name

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('clients/', HomeView.as_view(), name='clients'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_view/<int:pk>', MessageDetailView.as_view(), name='message_view'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('logs_view/', LogListView.as_view(), name='log_view'),
]


start_scheduler()

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyView, UserUpdateView, generate_new_password, \
    UserListView, deactivate_user, activate_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('user_view/', UserListView.as_view(), name='user_view'),
    path('deactivate_user/<int:pk>/', deactivate_user, name='deactivate_user'),
    path('activate_user/<int:pk>/', activate_user, name='activate_user'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.conf import settings
from django.db import models
from datetime import timedelta
from django.utils import timezone

NULLABLE = {'blank': True, 'null': True}


class Client(models.Model):
    email = models.EmailField(verbose_name='Email')
    fullname = models.CharField(max_length=255, verbose_name='ФИО')
    comment = models.TextField(**NULLABLE, verbose_name='Комментарий')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.fullname} {self.comment} {self.email}'

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'


class Message(models.Model):
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Контент')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.title} {self.content}'

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'


class Mailing(models.Model):
    TIME_CHOICES = (
        ('daily', 'Раз в день'),
        ('weekly', 'Раз в неделю'),
        ('monthly', 'Раз в месяц'),
    )
    STATUS_CHOICES = (
        ('completed', 'Завершена'),
        ('created', 'Создана'),
        ('started', 'Запущена'),
    )
    period = models.CharField(max_length=10, choices=TIME_CHOICES, verbose_name='Период')
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created', verbose_name='Статус')
    time = models.TimeField(verbose_name='Время')
    next_run = models.DateField(verbose_name='Следующий запуск')
    message = models.ForeignKey(Message, on_delete=models.CASCADE, default=1, verbose_name='Сообщения')
    clients = models.ManyToManyField(Client, verbose_name='Клиенты')
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.time} {self.period} {self.status}'

    class Meta:
        verbose_name = 'Рассылка'
        verbose_name_plural = 'Рассылки'

    def start_mailing(self):
        # Устанавливаем статус рассылки "Started"
        self.status = 'started'
        self.save()
        # Обновляем дату следующего запуска
        if self.period == 'daily':
            self.next_run += timedelta(days=1)
        elif self.period == 'weekly':
            self.next_run += timedelta(weeks=1)
        elif self.period == 'monthly':
            self.next_run += timedelta(days=30)
        # Устанавливаем статус рассылки «created», если следующая дата запуска наступит в будущем.
        if self.next_run > timezone.now().date():
            self.status = 'created'
        else:
            self.status = 'started'
        self.save()


class MailingLog(models.Model):
    date_time = models.DateTimeField(verbose_name='Дата и время')
    status = models.CharField(max_length=10, verbose_name='Статус')
    server_response = models.TextField(**NULLABLE, verbose_name='Ответ сервера')
    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='Пользователь',
                             **NULLABLE)

    def __str__(self):
        return f'{self.date_time} {self.status} {self.server_response} {self.mailing}'

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

client/forms.py
from django import forms

from client.models import Client, Mailing, Message


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ClientForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Client
        fields = ('email', 'fullname', 'comment')


class MailingForm(StyleFormMixin, forms.ModelForm):
    clients = forms.ModelMultipleChoiceField(queryset=None)
    message = forms.ModelChoiceField(queryset=None)

    class Meta:
        model = Mailing
        fields = ['period', 'status', 'time', 'next_run', 'clients', 'message']

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user')
        super().__init__(*args, **kwargs)
        self.fields['clients'].queryset = Client.objects.filter(user=user)
        self.fields['message'].queryset = Message.objects.filter(user=user)
        # self.initial['user'] = user


class MessageForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Message
        fields = ('title', 'content')

client/views.py
from random import sample

from django.core.cache import cache
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView

from django.contrib.auth.mixins import LoginRequiredMixin

from blogpost.models import Blogpost
from client.forms import ClientForm, MailingForm, MessageForm
from client.models import Client, Mailing, Message, MailingLog
from client.services import get_main_page_data


# Как только логику вынес в сервисный файл, кеширование стало работать намного медленнее
def main_page(request):
    data = get_main_page_data()
    return render(request, 'client/main_page.html', data)


class LogListView(LoginRequiredMixin, ListView):
    model = MailingLog
    template_name = 'client/logs.html'
    context_object_name = 'logs'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class HomeView(LoginRequiredMixin, ListView):
    model = Client
    template_name = 'client/clients.html'
    extra_context = {
        'title': 'Клиенты'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class ClientCreateView(LoginRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    # fields = ('fullname', 'email', 'comment',)
    success_url = reverse_lazy('client:clients')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class ClientDetailView(DetailView):
    model = Client
    template_name = 'client/detail.html'


class ClientUpdateView(LoginRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('client:clients')


class ClientDeleteView(LoginRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('client:clients')


class MailingListView(LoginRequiredMixin, ListView):
    model = Mailing
    fields = ('time', 'period', 'status', 'clients')
    extra_context = {
        'title': 'Рассылки'
    }
    success_url = reverse_lazy('mailing:list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('client:mailing_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDetailView(DetailView):
    model = Mailing
    template_name = 'client/mailing_detail.html'


class MailingUpdateView(LoginRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('client:mailing_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs


class MailingDeleteView(LoginRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('client:mailing_list')


class MessageListView(LoginRequiredMixin, ListView):
    model = Message
    fields = ('title', 'content')
    extra_context = {
        'title': 'Сообщения'
    }
    success_url = reverse_lazy('message:list')

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        return queryset


class MessageCreateView(LoginRequiredMixin, CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('client:message_list')

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class MessageDetailView(DetailView):
    model = Message
    template_name = 'client/message_detail.html'


class MessageUpdateView(LoginRequiredMixin, UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('client:message_list')


class MessageDeleteView(LoginRequiredMixin, DeleteView):
    model = Message
    success_url = reverse_lazy('client:message_list')

client/templates/client/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О нас</h4>
                    <p class="text-muted">Меня надо заполнить!</p>
                </div>
                {% include 'client/includes/inc_main_menu.html' %}
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="#" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none"
                     stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path>
                    <circle cx="12" cy="13" r="4"></circle>
                </svg>
                <strong>SuperPuperService</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>

<footer class="text-muted">
    <div class="container">
        <p>&copy; {% now 'Y' %}</p>
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

client/templates/client/client_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить клиента"{{object.title}}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'client:clients'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/client_form.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/clients.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'client:client_create' %}">Добавить клиента</a>
        </div>
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">{{ object.fullname }}</p>
                        <p class="card-text">{{ object.comment }}</p>
                        <p class="card-text">{{ object.email }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'client:view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                <a href="{% url 'client:client_update' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-warning">Редактировать</a>
                                <a href="{% url 'client:client_delete' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'client:main_page' %}">На главную</a>
    </div>
</footer>
{% endblock %}

client/templates/client/detail.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.fullname }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.comment }}
                        </p>

                    </div>
                    <div class="card-footer">
                        {{ object.email }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/logs.html
{% extends 'client/base.html' %}

{% block content %}
  <h1>{{ title }}</h1>
  <table>
    <thead>
      <tr>
        <th>Дата и время</th>
        <th>Статус</th>
        <th>Ответ сервера</th>
      </tr>
    </thead>
    <tbody>
      {% for log in object_list %}
        <tr>
          <td>{{ log.date_time }}</td>
          <td>{{ log.status }}</td>
          <td>{{ log.server_response }}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
  <style>
    table {
      border-collapse: collapse;
      width: 100%;
    }

    th, td {
      text-align: left;
      padding: 8px;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>
    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
            <a href="{% url 'client:main_page' %}">На главную</a>
        </div>
    </footer>
{% endblock %}

client/templates/client/mailing_detail.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.time }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.period }}
                        </p>

                    </div>
                    <div class="card-footer">
                        {{ object.status }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/mailing_form.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/mailing_list.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'client:mailing_create' %}">Добавить рассылку</a>
        </div>
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">{{ object.time }}</p>
                        <p class="card-text">{{ object.period }}</p>
                        <p class="card-text">{{ object.status }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'client:mailing_view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                <a href="{% url 'client:mailing_update' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-warning">Редактировать</a>
                                <a href="{% url 'client:mailing_delete' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'client:main_page' %}">На главную</a>
    </div>
</footer>
{% endblock %}

client/templates/client/main_page.html
{% extends 'client/base.html' %}
{% block content %}
<div class="col-12 mb-5">

<div class="row">
        <div class="col-1-3">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">Количество рассылок всего: {{ num_mailings }}</p>
                    <p class="card-text">Количество активных рассылок: {{ num_active_mailings }}</p>
                    <p class="card-text">Количество уникальных клиентов для рассылок: {{ num_unique_clients }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="col-1-3">
                            {% if random_articles %}
                            <h2>Случайные статьи из блога:</h2>
                            <ul>
                            {% for article in random_articles %}
                            <li><h3>{{ article.title }}</h3><p>{{ article.content }}</p></li>
                            {% endfor %}
                            </ul>
                            {% else %}
                            <p>В блоге нет статей.</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
</div>

{% endblock %}

client/templates/client/message_confirm_delete.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить сообщение"{{object.time}}?"</p>
                        <button type="submit" class="btn btn-danger">Подтвердить</button>
                        <a href="{% url 'client:message_list'%}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_detail.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            {{ object.title }}
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_form.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

client/templates/client/message_list.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-12 mb-5">
            <a class="btn btn-primary" href="{% url 'client:message_create' %}">Добавить сообщение</a>
        </div>
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.content }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a href="{% url 'client:message_view' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                <a href="{% url 'client:message_update' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-warning">Редактировать</a>
                                <a href="{% url 'client:message_delete' object.pk %}" type="button"
                                   class="btn btn-sm btn-outline-danger">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'client:main_page' %}">На главную</a>
    </div>
</footer>
{% endblock %}