client/urls.py
from django.urls import path

from . import views
from .apps import ClientConfig
from .services import start_scheduler
from .views import HomeView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingListView, \
    MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, MessageListView, MessageCreateView, \
    MessageUpdateView, MessageDetailView, MessageDeleteView, LogListView

app_name = ClientConfig.name

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('clients/', HomeView.as_view(), name='clients'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_view/<int:pk>', MessageDetailView.as_view(), name='message_view'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('logs_view/', LogListView.as_view(), name='log_view'),
]


start_scheduler()

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyView, UserUpdateView, generate_new_password, \
    UserListView, deactivate_user, activate_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('user_view/', UserListView.as_view(), name='user_view'),
    path('deactivate_user/<int:pk>/', deactivate_user, name='deactivate_user'),
    path('activate_user/<int:pk>/', activate_user, name='activate_user'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
import secrets

from django.contrib.auth.models import AbstractUser
from django.db import models

from client.models import NULLABLE


class User(AbstractUser):
    username = None

    email = models.EmailField(unique=True, verbose_name='Email')

    phone = models.CharField(max_length=35, verbose_name='Номер телефона', **NULLABLE)
    country = models.CharField(max_length=100, verbose_name='Страна', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='Аватар', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    verification_token = models.CharField(max_length=64, blank=True)

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def generate_verification_token(self):
        token = secrets.token_urlsafe(32)
        self.verification_token = token
        self.save()
        return token

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from client.forms import StyleFormMixin
from users.models import User


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserForm(StyleFormMixin, UserChangeForm):
    pass

    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone', 'country', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password'].widget = forms.HiddenInput()

users/views.py
import random

from django.conf import settings
from django.contrib.auth import login, authenticate, get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView as BaseLoginView
from django.contrib.auth.views import LogoutView as BaseLogoutView
from django.core.mail import send_mail
from django.http import HttpResponseBadRequest
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, TemplateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserForm
from users.models import User


class LoginView(BaseLoginView):
    template_name = 'users/login.html'


class LogoutView(BaseLogoutView):
    pass


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('client:main_page')
    template_name = 'users/register.html'

    def form_valid(self, form):
        # Сохраняем объект пользователя
        response = super().form_valid(form)
        # Отправляем пользователю электронное письмо с подтверждением
        user = form.save(commit=False)
        token = user.generate_verification_token()
        user.save()
        send_mail(
            subject='Подтверждение регистрации',
            message=f'Для подтверждения регистрации на сайте перейдите по ссылке: {self.request.build_absolute_uri(reverse_lazy("users:verify", kwargs={"token": token}))}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return response


class VerifyView(TemplateView):
    template_name = 'users/verify.html'

    def get(self, request, *args, **kwargs):
        token = kwargs.get('token')
        try:
            user = User.objects.get(verification_token=token)
            user.is_verified = True
            user.save()
            login(request, user)
            return redirect('client:main_page')
        except User.DoesNotExist:
            return HttpResponseBadRequest('Invalid verification token')


class UserUpdateView(UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserForm

    def get_object(self, queryset=None):
        return self.request.user


def generate_new_password(request):
    new_password = ''.join([str(random.randint(0, 9)) for _ in range(10)])
    send_mail(
        subject='Вы сменили пароль',
        message=f'Ваш новый пароль: {new_password}',
        from_email=settings.EMAIL_HOST_USER,
        recipient_list=[request.user.email],
    )
    user = request.user
    user.set_password(new_password)
    user.save()
    login(request, user)
    return redirect(reverse('users:profile'))


# class UserListView(LoginRequiredMixin, ListView):
#     model = User
#     fields = ('title', 'content')
#     extra_context = {
#         'title': 'Пользователи'
#     }

class UserListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    model = get_user_model()
    fields = ('title', 'content')
    extra_context = {
        'title': 'Пользователи'
    }
    success_url = reverse_lazy('client:main_page')

    def test_func(self):
        return self.request.user.is_staff

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['users'] = get_user_model().objects.all()
        return context


def deactivate_user(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    user.is_active = False
    user.save()
    return redirect('users:user_view')


def activate_user(request, pk):
    User = get_user_model()
    user = get_object_or_404(User, pk=pk)
    user.is_active = True
    user.save()
    return redirect('users:user_view')

users/templates/users/login.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Вход</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header"></div>
            <div class="card-body">
                <form method="post">
                    {% csrf_token %}
                    <p>На указанный email будет выслано письмо для подтверждения регистрации на сайте</p>
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Регистрация</button>
                </form>
            </div>
            <div class="card-footer"></div>
        </div>
    </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
    <div class="col-3"></div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>
            <div class="card-footer">
                <a href="{% url 'users:generate_new_password' %}" class="btn btn-danger">Сгенерировать пароль</a>
            </div>
        </div>
    </div>
    </div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="row">
        {% for object in object_list %}
            <div class="col-md-4">
                <div class="card mb-4 box-shadow">
                    <div class="card-body">
                        <p class="card-text">{{ object.email }}</p>
                        <p class="card-text">{{ object.first_name }} {{ object.last_name }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            {% if request.user.is_staff %}
                                <div class="btn-group">
                                    {% if object.is_active %}
                                    <a href="{% url 'users:deactivate_user' object.pk %}" type="button" class="btn btn-sm btn-outline-danger">Отключить</a>
                                    {% else %}
                                    <a href="{% url 'users:activate_user' object.pk %}" type="button" class="btn btn-sm btn-outline-success">Включить</a>
                                    {% endif %}
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>

    <footer class="text-muted">
        <div class="container">
            <p class="float-right">
                <a href="{% url 'client:main_page' %}">На главную</a>
            </p>
        </div>
    </footer>
{% endblock %}

users/templates/users/verify.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Подтверждение регистрации</title>
</head>
<body>
    <h1>Подтверждение регистрации</h1>
    <p>Вы успешно зарегистрировались на нашем сайте. Для завершения регистрации, пожалуйста, подтвердите свой адрес электронной почты, перейдя по ссылке, которая была отправлена на вашу почту.</p>
</body>
</html>