blogpost/urls.py
from django.urls import path

from blogpost.apps import BlogpostConfig
from blogpost.views import BlogpostListView, BlogpostDetailView
from django.views.decorators.cache import cache_page

app_name = BlogpostConfig.name


urlpatterns = [
    path('', BlogpostListView.as_view(), name='blogpost_list'),
    path('view/<int:pk>', cache_page(60)(BlogpostDetailView.as_view()), name='view'),
]

client/urls.py
from django.urls import path

from . import views
from .apps import ClientConfig
from .services import start_scheduler
from .views import HomeView, ClientCreateView, ClientDetailView, ClientUpdateView, ClientDeleteView, MailingListView, \
    MailingCreateView, MailingDetailView, MailingUpdateView, MailingDeleteView, MessageListView, MessageCreateView, \
    MessageUpdateView, MessageDetailView, MessageDeleteView, LogListView

app_name = ClientConfig.name

urlpatterns = [
    path('', views.main_page, name='main_page'),
    path('clients/', HomeView.as_view(), name='clients'),
    path('create/', ClientCreateView.as_view(), name='client_create'),
    path('view/<int:pk>', ClientDetailView.as_view(), name='view'),
    path('update/<int:pk>', ClientUpdateView.as_view(), name='client_update'),
    path('delete/<int:pk>', ClientDeleteView.as_view(), name='client_delete'),
    path('mailing/', MailingListView.as_view(), name='mailing_list'),
    path('mailing_create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailing_view/<int:pk>', MailingDetailView.as_view(), name='mailing_view'),
    path('mailing_update/<int:pk>', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailing_delete/<int:pk>', MailingDeleteView.as_view(), name='mailing_delete'),
    path('message/', MessageListView.as_view(), name='message_list'),
    path('message_create/', MessageCreateView.as_view(), name='message_create'),
    path('message_view/<int:pk>', MessageDetailView.as_view(), name='message_view'),
    path('message_update/<int:pk>', MessageUpdateView.as_view(), name='message_update'),
    path('message_delete/<int:pk>', MessageDeleteView.as_view(), name='message_delete'),
    path('logs_view/', LogListView.as_view(), name='log_view'),
]


start_scheduler()

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls', namespace='client')),
    path('users/', include('users.urls', namespace='users')),
    path('blogpost/', include('blogpost.urls', namespace='blogpost'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from users.apps import UsersConfig
from users.views import LoginView, LogoutView, RegisterView, VerifyView, UserUpdateView, generate_new_password, \
    UserListView, deactivate_user, activate_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('verify/<str:token>/', VerifyView.as_view(), name='verify'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('profile/genpassword/', generate_new_password, name='generate_new_password'),
    path('user_view/', UserListView.as_view(), name='user_view'),
    path('deactivate_user/<int:pk>/', deactivate_user, name='deactivate_user'),
    path('activate_user/<int:pk>/', activate_user, name='activate_user'),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogpost/models.py
from django.db import models

from client.models import NULLABLE


class Blogpost(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    content = models.TextField(**NULLABLE, verbose_name='содержимое')
    preview = models.ImageField(upload_to='blogposts/', **NULLABLE, verbose_name='изображение (превью)')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    is_published = models.BooleanField(default=True, verbose_name='опубликовано')
    views_count = models.IntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title} {self.content}'

    class Meta:
        verbose_name = 'Публикация'
        verbose_name_plural = 'Публикации'

blogpost/views.py
from django.views.generic import ListView, DetailView

from blogpost.models import Blogpost


class BlogpostListView(ListView):
    model = Blogpost

    extra_context = {
        'title': 'Наш блог!'
    }

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(is_published=True)
        return queryset


class BlogpostDetailView(DetailView):
    model = Blogpost

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object

blogpost/templates/blogpost/blogpost_detail.html
{% extends 'client/base.html' %}

{% block content %}
    <div class="col-12">
        <div class="row">

            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <img src="/media/{{ object.preview }}" class="card-img-top img-fluid"/>
                        <h3 class="card-title">
                            "{{ object.title }}"
                        </h3>
                    </div>
                    <div class="card-body">
                        <p>
                            {{ object.content }}
                        </p>

                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.views_count }}
                    </div>
                    <div class="card-footer">
                        Дата публикации: {{ object.created_at }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

blogpost/templates/blogpost/blogpost_list.html
{% extends 'client/base.html' %}
{% block content %}
<div class="col-12 mb-5">

<div class="row">
    {% for object in object_list %}
        <div class="col-md-4">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <p class="card-text">{{ object.title|title }}</p>
                    <div class="d-flex justify-content-between align-items-center">
                        <div class="btn-group">
                            <a href="{% url 'blogpost:view' object.pk %}" class="btn btn-sm btn-outline-secondary">Просмотр</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
</div>
<footer class="text-muted">
    <div class="container">
        <p class="float-right">
            <a href="{% url 'client:main_page' %}">На главную</a>
    </div>
</footer>
{% endblock %}